sudo: false
language: node_js
node_js:
  - "10"

addons:
  sonarcloud:
    organization: "petruki"
    token:
      secure: ${SONAR_TOKEN}

jobs:
  include:
    - stage: compile
      script:
        - npm install
    - stage: test
      script:
        - npm test
        - sonar-scanner

stages:
  - compile
  - test

after_success: npm run coveralls

services:
  - mongodb