language: node_js
node_js:
  - "10"

addons:
  sonarcloud:
    organization: "petruki"
    token:
      secure: ${SONAR_TOKEN}

jobs:
  include:
    - stage: compile
      script:
        - npm install
    - stage: test
      script:
        - npm test
        - sonar-scanner
    - stage: deploy
      script:
        - echo "Deploying to Heroku"
      deploy:
        provider: heroku
        app: switcher-api
          staging: switcher-api-staging
          production: switcher-api
        api_key:
          secure: ${HEROKU_KEY}

stages:
  - compile
  - test
  - deploy

after_success: npm run coveralls

services:
  - mongodb