language: node_js
node_js:
  - "10"

addons:
  sonarcloud:
    organization: "petruki"
    token:
      secure: ${SONAR_TOKEN}

jobs:
  include:
    - stage: compile
      script:
        - npm install
    - stage: test
      script:
        - npm test
        - sonar-scanner
    - stage: deploy to staging
      script:
        - echo "Deploying to Staging"
      deploy:
        provider: heroku
        app: switcher-api-staging
        api_key:
          secure: ${HEROKU_KEY}
    - stage: deploy to production
      script:
        - echo "Deploying to Production"
      deploy:
        provider: heroku
        app: switcher-api
        api_key:
          secure: ${HEROKU_KEY}

stages:
  - compile
  - test
  - deploy to staging
  - deploy to production

after_success: npm run coveralls

services:
  - mongodb